// Generated by Dagger (https://dagger.dev).
package clock.ui.alarm;

import com.yassineabou.clock.data.manager.ScheduleAlarmManager;
import com.yassineabou.clock.data.repository.AlarmRepository;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class AlarmViewModel_Factory implements Factory<AlarmViewModel> {
  private final Provider<AlarmRepository> alarmRepositoryProvider;

  private final Provider<ScheduleAlarmManager> scheduleAlarmManagerProvider;

  public AlarmViewModel_Factory(Provider<AlarmRepository> alarmRepositoryProvider,
      Provider<ScheduleAlarmManager> scheduleAlarmManagerProvider) {
    this.alarmRepositoryProvider = alarmRepositoryProvider;
    this.scheduleAlarmManagerProvider = scheduleAlarmManagerProvider;
  }

  @Override
  public AlarmViewModel get() {
    return newInstance(alarmRepositoryProvider.get(), scheduleAlarmManagerProvider.get());
  }

  public static AlarmViewModel_Factory create(Provider<AlarmRepository> alarmRepositoryProvider,
      Provider<ScheduleAlarmManager> scheduleAlarmManagerProvider) {
    return new AlarmViewModel_Factory(alarmRepositoryProvider, scheduleAlarmManagerProvider);
  }

  public static AlarmViewModel newInstance(AlarmRepository alarmRepository,
      ScheduleAlarmManager scheduleAlarmManager) {
    return new AlarmViewModel(alarmRepository, scheduleAlarmManager);
  }
}
