// Generated by Dagger (https://dagger.dev).
package clock.ui.timer;

import com.yassineabou.clock.data.manager.TimerManager;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class TimerViewModel_Factory implements Factory<TimerViewModel> {
  private final Provider<TimerManager> timerManagerProvider;

  public TimerViewModel_Factory(Provider<TimerManager> timerManagerProvider) {
    this.timerManagerProvider = timerManagerProvider;
  }

  @Override
  public TimerViewModel get() {
    return newInstance(timerManagerProvider.get());
  }

  public static TimerViewModel_Factory create(Provider<TimerManager> timerManagerProvider) {
    return new TimerViewModel_Factory(timerManagerProvider);
  }

  public static TimerViewModel newInstance(TimerManager timerManager) {
    return new TimerViewModel(timerManager);
  }
}
