// Generated by Dagger (https://dagger.dev).
package clock.data.receiver;

import com.yassineabou.clock.data.manager.ScheduleAlarmManager;
import com.yassineabou.clock.data.manager.WorkRequestManager;

import javax.inject.Provider;

import dagger.MembersInjector;
import dagger.internal.DaggerGenerated;
import dagger.internal.InjectedFieldSignature;
import dagger.internal.QualifierMetadata;

@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class AlarmBroadcastReceiver_MembersInjector implements MembersInjector<AlarmBroadcastReceiver> {
  private final Provider<ScheduleAlarmManager> scheduleAlarmManagerProvider;

  private final Provider<WorkRequestManager> workRequestManagerProvider;

  public AlarmBroadcastReceiver_MembersInjector(
      Provider<ScheduleAlarmManager> scheduleAlarmManagerProvider,
      Provider<WorkRequestManager> workRequestManagerProvider) {
    this.scheduleAlarmManagerProvider = scheduleAlarmManagerProvider;
    this.workRequestManagerProvider = workRequestManagerProvider;
  }

  public static MembersInjector<AlarmBroadcastReceiver> create(
      Provider<ScheduleAlarmManager> scheduleAlarmManagerProvider,
      Provider<WorkRequestManager> workRequestManagerProvider) {
    return new AlarmBroadcastReceiver_MembersInjector(scheduleAlarmManagerProvider, workRequestManagerProvider);
  }

  @Override
  public void injectMembers(AlarmBroadcastReceiver instance) {
    injectScheduleAlarmManager(instance, scheduleAlarmManagerProvider.get());
    injectWorkRequestManager(instance, workRequestManagerProvider.get());
  }

  @InjectedFieldSignature("com.yassineabou.clock.data.receiver.AlarmBroadcastReceiver.scheduleAlarmManager")
  public static void injectScheduleAlarmManager(AlarmBroadcastReceiver instance,
      ScheduleAlarmManager scheduleAlarmManager) {
    instance.scheduleAlarmManager = scheduleAlarmManager;
  }

  @InjectedFieldSignature("com.yassineabou.clock.data.receiver.AlarmBroadcastReceiver.workRequestManager")
  public static void injectWorkRequestManager(AlarmBroadcastReceiver instance,
      WorkRequestManager workRequestManager) {
    instance.workRequestManager = workRequestManager;
  }
}
