// Generated by Dagger (https://dagger.dev).
package clock.data.receiver;

import com.yassineabou.clock.data.manager.StopwatchManager;
import com.yassineabou.clock.util.helper.StopwatchNotificationHelper;

import javax.inject.Provider;

import dagger.MembersInjector;
import dagger.internal.DaggerGenerated;
import dagger.internal.InjectedFieldSignature;
import dagger.internal.QualifierMetadata;

@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class StopwatchNotificationBroadcastReceiver_MembersInjector implements MembersInjector<StopwatchNotificationBroadcastReceiver> {
  private final Provider<StopwatchManager> stopwatchManagerProvider;

  private final Provider<StopwatchNotificationHelper> stopwatchNotificationHelperProvider;

  public StopwatchNotificationBroadcastReceiver_MembersInjector(
      Provider<StopwatchManager> stopwatchManagerProvider,
      Provider<StopwatchNotificationHelper> stopwatchNotificationHelperProvider) {
    this.stopwatchManagerProvider = stopwatchManagerProvider;
    this.stopwatchNotificationHelperProvider = stopwatchNotificationHelperProvider;
  }

  public static MembersInjector<StopwatchNotificationBroadcastReceiver> create(
      Provider<StopwatchManager> stopwatchManagerProvider,
      Provider<StopwatchNotificationHelper> stopwatchNotificationHelperProvider) {
    return new StopwatchNotificationBroadcastReceiver_MembersInjector(stopwatchManagerProvider, stopwatchNotificationHelperProvider);
  }

  @Override
  public void injectMembers(StopwatchNotificationBroadcastReceiver instance) {
    injectStopwatchManager(instance, stopwatchManagerProvider.get());
    injectStopwatchNotificationHelper(instance, stopwatchNotificationHelperProvider.get());
  }

  @InjectedFieldSignature("com.yassineabou.clock.data.receiver.StopwatchNotificationBroadcastReceiver.stopwatchManager")
  public static void injectStopwatchManager(StopwatchNotificationBroadcastReceiver instance,
      StopwatchManager stopwatchManager) {
    instance.stopwatchManager = stopwatchManager;
  }

  @InjectedFieldSignature("com.yassineabou.clock.data.receiver.StopwatchNotificationBroadcastReceiver.stopwatchNotificationHelper")
  public static void injectStopwatchNotificationHelper(
      StopwatchNotificationBroadcastReceiver instance,
      StopwatchNotificationHelper stopwatchNotificationHelper) {
    instance.stopwatchNotificationHelper = stopwatchNotificationHelper;
  }
}
