// Generated by Dagger (https://dagger.dev).
package clock.data.manager;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class StopwatchManager_Factory implements Factory<StopwatchManager> {
  private final Provider<WorkRequestManager> workRequestManagerProvider;

  public StopwatchManager_Factory(Provider<WorkRequestManager> workRequestManagerProvider) {
    this.workRequestManagerProvider = workRequestManagerProvider;
  }

  @Override
  public StopwatchManager get() {
    return newInstance(workRequestManagerProvider.get());
  }

  public static StopwatchManager_Factory create(
      Provider<WorkRequestManager> workRequestManagerProvider) {
    return new StopwatchManager_Factory(workRequestManagerProvider);
  }

  public static StopwatchManager newInstance(WorkRequestManager workRequestManager) {
    return new StopwatchManager(workRequestManager);
  }
}
