// Generated by Dagger (https://dagger.dev).
package clock.data.workManager.factory;

import com.yassineabou.clock.data.manager.WorkRequestManager;
import com.yassineabou.clock.data.repository.AlarmRepository;
import com.yassineabou.clock.util.helper.AlarmNotificationHelper;
import com.yassineabou.clock.util.helper.MediaPlayerHelper;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class AlarmWorkerFactory_Factory implements Factory<AlarmWorkerFactory> {
  private final Provider<AlarmRepository> alarmRepositoryProvider;

  private final Provider<AlarmNotificationHelper> alarmNotificationHelperProvider;

  private final Provider<MediaPlayerHelper> mediaPlayerHelperProvider;

  private final Provider<WorkRequestManager> workRequestManagerProvider;

  public AlarmWorkerFactory_Factory(Provider<AlarmRepository> alarmRepositoryProvider,
      Provider<AlarmNotificationHelper> alarmNotificationHelperProvider,
      Provider<MediaPlayerHelper> mediaPlayerHelperProvider,
      Provider<WorkRequestManager> workRequestManagerProvider) {
    this.alarmRepositoryProvider = alarmRepositoryProvider;
    this.alarmNotificationHelperProvider = alarmNotificationHelperProvider;
    this.mediaPlayerHelperProvider = mediaPlayerHelperProvider;
    this.workRequestManagerProvider = workRequestManagerProvider;
  }

  @Override
  public AlarmWorkerFactory get() {
    return newInstance(alarmRepositoryProvider.get(), alarmNotificationHelperProvider.get(), mediaPlayerHelperProvider.get(), workRequestManagerProvider.get());
  }

  public static AlarmWorkerFactory_Factory create(Provider<AlarmRepository> alarmRepositoryProvider,
      Provider<AlarmNotificationHelper> alarmNotificationHelperProvider,
      Provider<MediaPlayerHelper> mediaPlayerHelperProvider,
      Provider<WorkRequestManager> workRequestManagerProvider) {
    return new AlarmWorkerFactory_Factory(alarmRepositoryProvider, alarmNotificationHelperProvider, mediaPlayerHelperProvider, workRequestManagerProvider);
  }

  public static AlarmWorkerFactory newInstance(AlarmRepository alarmRepository,
      AlarmNotificationHelper alarmNotificationHelper, MediaPlayerHelper mediaPlayerHelper,
      WorkRequestManager workRequestManager) {
    return new AlarmWorkerFactory(alarmRepository, alarmNotificationHelper, mediaPlayerHelper, workRequestManager);
  }
}
