// Generated by Dagger (https://dagger.dev).
package clock.data.workManager.factory;

import com.yassineabou.clock.data.manager.ScheduleAlarmManager;
import com.yassineabou.clock.data.manager.WorkRequestManager;
import com.yassineabou.clock.data.repository.AlarmRepository;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RescheduleAlarmWorkerFactory_Factory implements Factory<RescheduleAlarmWorkerFactory> {
  private final Provider<AlarmRepository> alarmRepositoryProvider;

  private final Provider<ScheduleAlarmManager> scheduleAlarmManagerProvider;

  private final Provider<WorkRequestManager> workRequestManagerProvider;

  public RescheduleAlarmWorkerFactory_Factory(Provider<AlarmRepository> alarmRepositoryProvider,
      Provider<ScheduleAlarmManager> scheduleAlarmManagerProvider,
      Provider<WorkRequestManager> workRequestManagerProvider) {
    this.alarmRepositoryProvider = alarmRepositoryProvider;
    this.scheduleAlarmManagerProvider = scheduleAlarmManagerProvider;
    this.workRequestManagerProvider = workRequestManagerProvider;
  }

  @Override
  public RescheduleAlarmWorkerFactory get() {
    return newInstance(alarmRepositoryProvider.get(), scheduleAlarmManagerProvider.get(), workRequestManagerProvider.get());
  }

  public static RescheduleAlarmWorkerFactory_Factory create(
      Provider<AlarmRepository> alarmRepositoryProvider,
      Provider<ScheduleAlarmManager> scheduleAlarmManagerProvider,
      Provider<WorkRequestManager> workRequestManagerProvider) {
    return new RescheduleAlarmWorkerFactory_Factory(alarmRepositoryProvider, scheduleAlarmManagerProvider, workRequestManagerProvider);
  }

  public static RescheduleAlarmWorkerFactory newInstance(AlarmRepository alarmRepository,
      ScheduleAlarmManager scheduleAlarmManager, WorkRequestManager workRequestManager) {
    return new RescheduleAlarmWorkerFactory(alarmRepository, scheduleAlarmManager, workRequestManager);
  }
}
