// Generated by Dagger (https://dagger.dev).
package clock.data.workManager.worker;

import android.content.Context;

import com.yassineabou.clock.data.manager.WorkRequestManager;
import com.yassineabou.clock.data.repository.AlarmRepository;
import com.yassineabou.clock.util.helper.AlarmNotificationHelper;

import androidx.work.WorkerParameters;
import dagger.internal.DaggerGenerated;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class AlarmCheckerWorker_Factory {
  public AlarmCheckerWorker_Factory() {
  }

  public AlarmCheckerWorker get(AlarmRepository alarmRepository,
      AlarmNotificationHelper alarmNotificationHelper, WorkRequestManager workRequestManager,
      Context ctx, WorkerParameters params) {
    return newInstance(alarmRepository, alarmNotificationHelper, workRequestManager, ctx, params);
  }

  public static AlarmCheckerWorker_Factory create() {
    return new AlarmCheckerWorker_Factory();
  }

  public static AlarmCheckerWorker newInstance(AlarmRepository alarmRepository,
      AlarmNotificationHelper alarmNotificationHelper, WorkRequestManager workRequestManager,
      Context ctx, WorkerParameters params) {
    return new AlarmCheckerWorker(alarmRepository, alarmNotificationHelper, workRequestManager, ctx, params);
  }
}
