// Generated by Dagger (https://dagger.dev).
package clock.data.workManager.worker;

import android.content.Context;

import com.yassineabou.clock.data.manager.ScheduleAlarmManager;
import com.yassineabou.clock.data.manager.WorkRequestManager;
import com.yassineabou.clock.data.repository.AlarmRepository;

import androidx.work.WorkerParameters;
import dagger.internal.DaggerGenerated;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class RescheduleAlarmWorker_Factory {
  public RescheduleAlarmWorker_Factory() {
  }

  public RescheduleAlarmWorker get(AlarmRepository alarmRepository,
      ScheduleAlarmManager scheduleAlarmManager, WorkRequestManager workRequestManager, Context ctx,
      WorkerParameters params) {
    return newInstance(alarmRepository, scheduleAlarmManager, workRequestManager, ctx, params);
  }

  public static RescheduleAlarmWorker_Factory create() {
    return new RescheduleAlarmWorker_Factory();
  }

  public static RescheduleAlarmWorker newInstance(AlarmRepository alarmRepository,
      ScheduleAlarmManager scheduleAlarmManager, WorkRequestManager workRequestManager, Context ctx,
      WorkerParameters params) {
    return new RescheduleAlarmWorker(alarmRepository, scheduleAlarmManager, workRequestManager, ctx, params);
  }
}
