// Generated by Dagger (https://dagger.dev).
package clock.data.workManager.worker;

import android.content.Context;

import com.yassineabou.clock.data.manager.TimerManager;
import com.yassineabou.clock.util.helper.TimerNotificationHelper;

import androidx.work.WorkerParameters;
import dagger.internal.DaggerGenerated;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class TimerRunningWorker_Factory {
  public TimerRunningWorker_Factory() {
  }

  public TimerRunningWorker get(TimerManager timerManager,
      TimerNotificationHelper timerNotificationHelper, Context ctx, WorkerParameters params) {
    return newInstance(timerManager, timerNotificationHelper, ctx, params);
  }

  public static TimerRunningWorker_Factory create() {
    return new TimerRunningWorker_Factory();
  }

  public static TimerRunningWorker newInstance(TimerManager timerManager,
      TimerNotificationHelper timerNotificationHelper, Context ctx, WorkerParameters params) {
    return new TimerRunningWorker(timerManager, timerNotificationHelper, ctx, params);
  }
}
