// Generated by Dagger (https://dagger.dev).
package clock.data.workManager.worker;

import android.content.Context;

import com.yassineabou.clock.data.manager.TimerManager;
import com.yassineabou.clock.util.helper.MediaPlayerHelper;
import com.yassineabou.clock.util.helper.TimerNotificationHelper;

import androidx.work.WorkerParameters;
import dagger.internal.DaggerGenerated;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class TimerCompletedWorker_Factory {
  public TimerCompletedWorker_Factory() {
  }

  public TimerCompletedWorker get(MediaPlayerHelper mediaPlayerHelper,
      TimerNotificationHelper timerNotificationHelper, TimerManager timerManager, Context ctx,
      WorkerParameters params) {
    return newInstance(mediaPlayerHelper, timerNotificationHelper, timerManager, ctx, params);
  }

  public static TimerCompletedWorker_Factory create() {
    return new TimerCompletedWorker_Factory();
  }

  public static TimerCompletedWorker newInstance(MediaPlayerHelper mediaPlayerHelper,
      TimerNotificationHelper timerNotificationHelper, TimerManager timerManager, Context ctx,
      WorkerParameters params) {
    return new TimerCompletedWorker(mediaPlayerHelper, timerNotificationHelper, timerManager, ctx, params);
  }
}
