// Generated by Dagger (https://dagger.dev).
package clock.ui.stopwatch;

import com.yassineabou.clock.data.manager.StopwatchManager;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class StopwatchViewModel_Factory implements Factory<StopwatchViewModel> {
  private final Provider<StopwatchManager> stopwatchManagerProvider;

  public StopwatchViewModel_Factory(Provider<StopwatchManager> stopwatchManagerProvider) {
    this.stopwatchManagerProvider = stopwatchManagerProvider;
  }

  @Override
  public StopwatchViewModel get() {
    return newInstance(stopwatchManagerProvider.get());
  }

  public static StopwatchViewModel_Factory create(
      Provider<StopwatchManager> stopwatchManagerProvider) {
    return new StopwatchViewModel_Factory(stopwatchManagerProvider);
  }

  public static StopwatchViewModel newInstance(StopwatchManager stopwatchManager) {
    return new StopwatchViewModel(stopwatchManager);
  }
}
