// Generated by Dagger (https://dagger.dev).
package clock.util.helper;

import android.content.Context;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata("dagger.hilt.android.qualifiers.ApplicationContext")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class MediaPlayerHelper_Factory implements Factory<MediaPlayerHelper> {
  private final Provider<Context> applicationContextProvider;

  public MediaPlayerHelper_Factory(Provider<Context> applicationContextProvider) {
    this.applicationContextProvider = applicationContextProvider;
  }

  @Override
  public MediaPlayerHelper get() {
    return newInstance(applicationContextProvider.get());
  }

  public static MediaPlayerHelper_Factory create(Provider<Context> applicationContextProvider) {
    return new MediaPlayerHelper_Factory(applicationContextProvider);
  }

  public static MediaPlayerHelper newInstance(Context applicationContext) {
    return new MediaPlayerHelper(applicationContext);
  }
}
