// Generated by Dagger (https://dagger.dev).
package clock.util.helper;

import android.content.Context;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata("javax.inject.Singleton")
@QualifierMetadata("dagger.hilt.android.qualifiers.ApplicationContext")
@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes",
    "KotlinInternal",
    "KotlinInternalInJava"
})
public final class TimerNotificationHelper_Factory implements Factory<TimerNotificationHelper> {
  private final Provider<Context> applicationContextProvider;

  public TimerNotificationHelper_Factory(Provider<Context> applicationContextProvider) {
    this.applicationContextProvider = applicationContextProvider;
  }

  @Override
  public TimerNotificationHelper get() {
    return newInstance(applicationContextProvider.get());
  }

  public static TimerNotificationHelper_Factory create(
      Provider<Context> applicationContextProvider) {
    return new TimerNotificationHelper_Factory(applicationContextProvider);
  }

  public static TimerNotificationHelper newInstance(Context applicationContext) {
    return new TimerNotificationHelper(applicationContext);
  }
}
